### PR TITLE
Egyenletmegoldo-buntetohazi-v2

### PR DESCRIPTION
**Pull request by accacca44**
By :Kovacs Elek Akos X.B 2019.02.26

### CODE REVIEW

**Comment by accacca44** [comment]
Remelem most jo a hazi. Lehetseges hogy masodjara kapja meg a pull requestet, ha megsem ,az azt jelenti, hogy hulye vagyok es kitoroltem.

**Comment by sboda1985** [comment]
ez nem az erettsegi tetelekhez tartozik

**Comment by accacca44** [comment]
SrySaját Samsung Galaxy okostelefonról küldve.
-------- Eredeti üzenet --------Feladó: sboda1985 <notifications@github.com> Dátum: 2020. 02. 11.  7:14  (GMT+02:00) Címzett: sboda1985/erettsegi <erettsegi@noreply.github.com> Másolatot kap: accacca44 <kovacsakos36@gmail.com>, State change <state_change@noreply.github.com> Tárgy: Re: [sboda1985/erettsegi] Egyenletmegoldo-buntetohazi-v2 (#10) ez nem az erettsegi tetelekhez tartozik

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sboda1985/erettsegi/pull/10?email_source=notifications\u0026email_token=ALKZKSG77ASDSCYSW3H4SADRCIX3TA5CNFSM4G2L2BTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELLHRYQ#issuecomment-584480994",
"url": "https://github.com/sboda1985/erettsegi/pull/10?email_source=notifications\u0026email_token=ALKZKSG77ASDSCYSW3H4SADRCIX3TA5CNFSM4G2L2BTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELLHRYQ#issuecomment-584480994",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by accacca44** [comment]
Viszont olimpiász tételSaját Samsung Galaxy okostelefonról küldve.
-------- Eredeti üzenet --------Feladó: sboda1985 <notifications@github.com> Dátum: 2020. 02. 11.  7:14  (GMT+02:00) Címzett: sboda1985/erettsegi <erettsegi@noreply.github.com> Másolatot kap: accacca44 <kovacsakos36@gmail.com>, State change <state_change@noreply.github.com> Tárgy: Re: [sboda1985/erettsegi] Egyenletmegoldo-buntetohazi-v2 (#10) ez nem az erettsegi tetelekhez tartozik

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sboda1985/erettsegi/pull/10?email_source=notifications\u0026email_token=ALKZKSG77ASDSCYSW3H4SADRCIX3TA5CNFSM4G2L2BTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELLHRYQ#issuecomment-584480994",
"url": "https://github.com/sboda1985/erettsegi/pull/10?email_source=notifications\u0026email_token=ALKZKSG77ASDSCYSW3H4SADRCIX3TA5CNFSM4G2L2BTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELLHRYQ#issuecomment-584480994",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request closed without merging**
